name: actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use the latest Python 3.x version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run pyflakes
      #- name: Pyflakes Syntax Checker
      # uses: lgeiger/pyflakes-action@v1.0.1

      # Step 4: Run pyflakes
      - name: Run pyflakes
        run: pyflakes **/ # all python files
